# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.name = "rails-demo"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.hostname = "rails-demo"
  config.vm.network "public_network", :ip => "192.168.0.158", :mac => "080027e46432"

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbooks/main.yml"
  #   ansible.become = true
  # end

end
